### PR TITLE
WIP improve simulated route

### PR DESCRIPTION
**Pull request by frederoni**
WIP improving simulated route
Specifically slowing down for sharp turns.

### CODE REVIEW

**Comment by bsudekum** [comment]
@frederoni did you mean to commit all the playground work?

**Comment by frederoni** [comment]
Not sure. It might fit better in a separate repo but it's quite convenient to test algorithms and hypothesis in a Playground.

**Comment by bsudekum** [comment]
I guess I'm just not seeing the exact code which addresses the screenshot above.

**Comment by 1ec5** [comment]
@frederoni, does #226 completely supersede this PR, or do you still want to land the playground?

**Comment by frederoni** [comment]
I would like to be able to use a Playground when working on this stuff but playgrounds doesn't support testable imports and I have to copy/paste the source files manually and change the access control frequently so I don't want to merge this PR until I've found a decent workaround.

**Comment by bsudekum** [comment]
What's the status here?

**Comment by frederoni** [comment]
WWDC did not reveal any new convenient ways of using a Playground in combination with pre-built binaries and frameworks or support for testable imports.

**Pull request closed without merging**
