### PR TITLE
Make sure to resize the gradient view under the current Instruction Card during a layout change

### PR DESCRIPTION
**Pull request by avi-c**
Fix for one of the issues in #2695

### CODE REVIEW

**Comment by avi-c** [comment]
I think the issue with the failing tests is the need to update the image snapshots. I don't know why only those particular fail but I think the main difference between the snapshot and the rendered image are the use of corner radii and some font changes.

**Comment by jill-cardamon** [comment]
Makes sense. Lately, tests have been failing for iOS 14/Xcode 12, so it's weird that they're failing older iOS versions.

**Comment by avi-c** [comment]
@1ec5 - If I want to update the test assets, would that happen under this ticket or do we need a different one?

**Comment by 1ec5** [comment]
Can we update it as part of #2727?

**Comment by avi-c** [comment]
Returning to this since it's fallen through the cracks. I am still confident that the code is correct but the tests need updating.

@jill-cardamon - Can we combine your updating of the iOS 14 snapshots with including this PR so that everything can happen at once? Maybe we can merge this PR into your branch and regenerate the snapshots there, then merge it all in with #2727

**Comment by 1ec5** [comment]
Sorry that this PR fell through the cracks. Do you think we could try to revive it for v2.0, now that UI tests are once again working there?

**Comment by S2Ler** [comment]
This PR merged already as part of 99dfa32

**Pull request closed without merging**
