### PR TITLE
Update snapshot tests for iOS 14

### PR DESCRIPTION
**Pull request by jill-cardamon**
Snapshot tests are specific to a particular iOS version, so a lot of tests are failing locally. This PR is to update these tests to run for iOS 14.
- [x] copy screenshots from iOS 13 for iOS 14
- [x] for failed tests, replace them with screenshots that the test harness came up with

### CODE REVIEW

**Comment by jill-cardamon** [comment]
Some before-and-after screenshots for a failed test (testLanesManeuver for iPhone 8 Plus on iOS 13 and 14):
testLanesManeuver_iPhone_8_Plus_Portrait_iOS_13 5@3x
failed_testLanesManeuver_iPhone_8_Plus_Portrait_iOS_14 1@3x

**Comment by jill-cardamon** [comment]
additional before-and-after screenshots are in MapboxNavigationTests/FailureDiffs/ (see commit here: https://github.com/mapbox/mapbox-navigation-ios/pull/2727/commits/e40febdd53cdf54ac0943b37e3ca7677a8d3039a)

**Review by 1ec5 — COMMENTED** [review]
Thanks! Remove this line so that the iOS 14 build bot tests the newly added fixtures:

https://github.com/mapbox/mapbox-navigation-ios/blob/0f00c9d3e36791b479e0a72e7937c37c1c089d16/.circleci/config.yml#L244

**Review by 1ec5 — APPROVED** [review]

**Comment by 1ec5** [comment]
[CarPlayManagerTests is failing consistently](https://app.circleci.com/pipelines/github/mapbox/mapbox-navigation-ios/2423/workflows/bc93dde1-7ca2-4dbd-81e1-6ed0cd23fd99/jobs/26015):

```
Test Case '-[MapboxNavigationTests.CarPlayManagerSpec Previewing_routes__when_the_trip_is_not_customized_by_the_developer__previews_a_route_options_with_the_default_configuration]' started.
/Users/distiller/project/MapboxNavigationTests/CarPlayManagerTests.swift:459: error: -[MapboxNavigationTests.CarPlayManagerSpec Previewing_routes__when_the_trip_is_not_customized_by_the_developer__previews_a_route_options_with_the_default_configuration] : Unsupported object <CPMapTemplate: 0x600002257240> <identifier: 50FBBB49-01FB-464C-B3F3-5CB5E4FDBA6B, userInfo: (null), tabTitle: (null), tabImage: (null), showsTabBadge: 0> passed to setRootTemplate:animated:completion:. Allowed classes: (null) (NSInvalidArgumentException)
Test Case '-[MapboxNavigationTests.CarPlayManagerSpec Previewing_routes__when_the_trip_is_not_customized_by_the_developer__previews_a_route_options_with_the_default_configuration]' failed (0.603 seconds).
Test Case '-[MapboxNavigationTests.CarPlayManagerSpec Previewing_routes__when_the_delegate_provides_a_custom_trip__shows_trip_previews_for_the_custom_trip]' started.
/Users/distiller/project/MapboxNavigationTests/CarPlayManagerTests.swift:459: error: -[MapboxNavigationTests.CarPlayManagerSpec Previewing_routes__when_the_delegate_provides_a_custom_trip__shows_trip_previews_for_the_custom_trip] : Unsupported object <CPMapTemplate: 0x600002262d00> <identifier: BEBDC7B5-FCB9-4DB4-9AA6-B66609F435C6, userInfo: (null), tabTitle: (null), tabImage: (null), showsTabBadge: 0> passed to setRootTemplate:animated:completion:. Allowed classes: (null) (NSInvalidArgumentException)
Test Case '-[MapboxNavigationTests.CarPlayManagerSpec Previewing_routes__when_the_delegate_provides_a_custom_trip__shows_trip_previews_for_the_custom_trip]' failed (0.015 seconds).
Test Case '-[MapboxNavigationTests.CarPlayManagerSpec Previewing_routes__when_the_delegate_provides_a_custom_trip_preview_text__previews_a_route_options_with_the_custom_trip_configuration]' started.
/Users/distiller/project/MapboxNavigationTests/CarPlayManagerTests.swift:459: error: -[MapboxNavigationTests.CarPlayManagerSpec Previewing_routes__when_the_delegate_provides_a_custom_trip_preview_text__previews_a_route_options_with_the_custom_trip_configuration] : Unsupported object <CPMapTemplate: 0x6000022506c0> <identifier: D1E6DA4D-3B27-4FAF-9DFD-1012C0870FCB, userInfo: (null), tabTitle: (null), tabImage: (null), showsTabBadge: 0> passed to setRootTemplate:animated:completion:. Allowed classes: (null) (NSInvalidArgumentException)
Test Case '-[MapboxNavigationTests.CarPlayManagerSpec Previewing_routes__when_the_delegate_provides_a_custom_trip_preview_text__previews_a_route_options_with_the_custom_trip_configuration]' failed (0.013 seconds).
Test Case '-[MapboxNavigationTests.CarPlayManagerSpec Starting_a_trip__When_configured_to_simulate__starts_navigation_with_a_navigation_service_with_simulation_enabled]' started.
/Users/distiller/project/MapboxNavigationTests/CarPlayManagerTests.swift:459: error: -[MapboxNavigationTests.CarPlayManagerSpec Starting_a_trip__When_configured_to_simulate__starts_navigation_with_a_navigation_service_with_simulation_enabled] : Unsupported object <CPMapTemplate: 0x600002252e80> <identifier: 25EC616C-D85A-4264-B9EC-EF35E0C55754, userInfo: (null), tabTitle: (null), tabImage: (null), showsTabBadge: 0> passed to setRootTemplate:animated:completion:. Allowed classes: (null) (NSInvalidArgumentException)
Test Case '-[MapboxNavigationTests.CarPlayManagerSpec Starting_a_trip__When_configured_to_simulate__starts_navigation_with_a_navigation_service_with_simulation_enabled]' failed (0.013 seconds).
Test Case '-[MapboxNavigationTests.CarPlayManagerSpec Starting_a_trip__When_configured_not_to_simulate__starts_navigation_with_a_navigation_service_with_simulation_set_to_onPoorGPS_by_default]' started.
/Users/distiller/project/MapboxNavigationTests/CarPlayManagerTests.swift:459: error: -[MapboxNavigationTests.CarPlayManagerSpec Starting_a_trip__When_configured_not_to_simulate__starts_navigation_with_a_navigation_service_with_simulation_set_to_onPoorGPS_by_default] : Unsupported object <CPMapTemplate: 0x600002258780> <identifier: 9EE33E42-EEC5-49AB-BD12-110CA5186C7D, userInfo: (null), tabTitle: (null), tabImage: (null), showsTabBadge: 0> passed to setRootTemplate:animated:completion:. Allowed classes: (null) (NSInvalidArgumentException)
Test Case '-[MapboxNavigationTests.CarPlayManagerSpec Starting_a_trip__When_configured_not_to_simulate__starts_navigation_with_a_navigation_service_with_simulation_set_to_onPoorGPS_by_default]' failed (0.013 seconds).
```

I’m worried this means the hacky MapTemplateSpyProvider is no longer working with the CarPlay framework:

https://github.com/mapbox/mapbox-navigation-ios/blob/fd6d1d1c7067a78d4256b360d260b06a570835ba/MapboxNavigationTests/CarPlayManagerTests.swift#L295 https://github.com/mapbox/mapbox-navigation-ios/blob/9300b59960d29ad51a34d2720b799c1ad7f1279a/MapboxNavigationTests/CarPlayManagerTests.swift#L597-L601 https://github.com/mapbox/mapbox-navigation-ios/blob/9300b59960d29ad51a34d2720b799c1ad7f1279a/MapboxNavigationTests/CarPlayManagerTests.swift#L569

**Pull request merged**
