### PR TITLE
v1.4.1

### PR DESCRIPTION
**Pull request by 1ec5**
Updated the Xcode project and CocoaPods podspecs for v1.4.1. This patch release ensures that #2495 brings consistency in feedback behavior between v1._x_ and the upcoming v2.0 release. It also backports #3023 to resolve a build warning in Swift 5.4. As a patch release, it doesn’t require any changes to the installation instructions in the readme.

/cc @mapbox/navigation-ios

### CODE REVIEW

**Review by S2Ler — APPROVED** [review]
🚀

**Comment by S2Ler** [comment]
I can include https://github.com/mapbox/mapbox-navigation-ios/issues/3056 in the release, but not sure it worth it to be honest.

**Comment by 1ec5** [comment]
Oh yeah, I forgot about that issue. If it isn’t too much trouble, feel free to push the backported change, since it’s tightly scoped, the impact is well-understood, and the changelog entry is well-written.

**Review by MaximAlien — APPROVED** [review]

**Comment by S2Ler** [comment]
> Oh yeah, I forgot about that issue. If it isn’t too much trouble, feel free to push the backported change, since it’s tightly scoped, the impact is well-understood, and the changelog entry is well-written.

#3083

**Pull request merged**
