### PR TITLE
Fix buttons dip down

### LINKED ISSUE #451: After rerouting, buttons dip down
simulator screen shot aug 2 2017 2 08 10 pm

/cc @frederoni

### PR DESCRIPTION
**Pull request by frederoni**
Fixes #451 

@bsudekum 👀

### CODE REVIEW

**Comment by frederoni** [comment]
Oh, this is probably related to https://github.com/mapbox/mapbox-navigation-ios/commit/60a02ad94bd02f4089429f942ad79537ab8eb935

You're browsing while the alert level is low. It should be ignored if it's not the current step.

**Comment by bsudekum** [comment]
Hrm it should be showing the lanes for the swiped-to-step and using the alert level passed through here https://github.com/mapbox/mapbox-navigation-ios/commit/60a02ad94bd02f4089429f942ad79537ab8eb935#diff-292af689ce88d5b5aa06966456abc0e9R478 which is always .high

**Comment by frederoni** [comment]
It's possible for a step to be the first/current and last at the same time which resulted in:



these incorrect left and right overlays are fixed in https://github.com/mapbox/mapbox-navigation-ios/pull/452/commits/534d9f4ad8fb03d332fd4693eb316333d2574d1e

**Comment by bsudekum** [comment]
Looks good, only thing I'm seeing now is a slight delay when after incrementing the step and showing the lane view:

untitled

**Pull request merged**
