### PR TITLE
[CarPlay] Add delegate methods for CarPlay panning

### PR DESCRIPTION
**Pull request by JackMoseley2001**
### Description

Being able to access underlying CarPlay MapTemplate delegate methods can be extremely useful for applying custom updates for an app, for example updating the visibility of custom buttons (e.g. if not using the built in recenter button) or preventing the navigation bar from hiding automatically (currently the property is set back to `true` [here](https://github.com/mapbox/mapbox-navigation-ios/blob/43b56855335ffa95e028f99f3b68fe1fb27bb8dc/Sources/MapboxNavigation/CarPlayManager.swift#L884), which is often desired behaviour in most cases, but in some cases it would be good to override this based on a particular event.

### Implementation

- Adds 4 new delegate methods to `CarPlayManagerDelegate`:
    - `carPlayManager(_ carPlayManager: CarPlayManager, didBeginPanGesture template: CPMapTemplate)`
    - `carPlayManager(_ carPlayManager: CarPlayManager, didEndPanGesture template: CPMapTemplate)`
    - `carPlayManager(_ carPlayManager: CarPlayManager, willDismissPanningInterface template: CPMapTemplate)`
    - `carPlayManager(_ carPlayManager: CarPlayManager,  didDismissPanningInterface template: CPMapTemplate)`
- This is a non-breaking change, adding optional delegate methods for end users to implement if required

### CODE REVIEW

**Comment by kried** [comment]
@JackMoseley2001, thank you for your PR.
I included your changes in #4368 so that the tests run correctly.

**Comment by JackMoseley2001** [comment]
> @JackMoseley2001, thank you for your PR.
> 
> I included your changes in #4368 so that the tests run correctly.

Thank you for picking this up! 🙌

**Comment by kried** [comment]
@JackMoseley2001,  #4368 is merged, so I'm closing this pull request.

**Comment by JackMoseley2001** [comment]
Thank you for getting that through quickly 🎉

**Pull request closed without merging**
