### PR TITLE
Housekeeping required to update our CI to Xcode 9.4.1 on Bitrise

### PR DESCRIPTION
**Pull request by akitchen**
Also disables a performance test until work can be done to establish a
meaningful baseline

### CODE REVIEW

**Comment by akitchen** [comment]
LOL, never. Just taking the opportunity to clean out the old stuff while updating to the latest.

**Comment by bsudekum** [comment]
We're these test fixtures unused?

**Comment by akitchen** [comment]
Deleted fixtures were unused, mostly from test classes which were renamed or repurposed. #springcleaning

**Comment by akitchen** [comment]
That said, we might want to consider snapshot testing against more than one device size classes

**Pull request merged**
