### PR TITLE
Add stylable marker view

### PR DESCRIPTION
**Pull request by frederoni**
Added a stylable marker view. This view is not yet being used.

screenshot 2017-08-29 19 22 20

@bsudekum @mayagao 👀

### CODE REVIEW

**Comment by bsudekum** [comment]
@1ec5 how do you feel about this? The goal here is to move more into the `Style` class.

**Comment by mayagao** [comment]
screen shot 2017-08-30 at 12 56 30 pm

@frederoni could we add a little white circle in the middle?

**Comment by frederoni** [comment]
@1ec5 @bsudekum 
If you want animations or a completely different marker view, you'd still want to implement `viewFor:`. This is just a convenient way to change the tint color, stroke color and shadow of the default marker.

**Comment by frederoni** [comment]
@mayagao 

Here's the most recent with the inner circle:

screenshot 2017-08-30 13 47 10

**Comment by 1ec5** [comment]
@frederoni, would you mind upstreaming this work to the map SDK? mapbox/mapbox-gl-native#2250

**Pull request merged**
