### PR TITLE
Move constraints from storyboard into components

### LINKED ISSUE #844: Status view can grow in height
When we flood the `statusView` with too many "statuses" it can get confused and grow 2x in height and animate back and forth. 

/cc @frederoni

### PR DESCRIPTION
**Pull request by frederoni**
Fixes #844 

This PR moves constraints responsible for the intrinsic content size away from the storyboard into each component (Next banner, status view, lanes).

@bsudekum @JThramer 👀

### CODE REVIEW

**Comment by bsudekum** [comment]
Looking good. While we're at it, can we fix the issue where the `Rerouting` text is still visible while the status view is sliding back up? It happens very momentarily.

**Comment by bsudekum** [comment]
Rerouting when the laneview was visible on the previous route:
simulator screen shot - iphone 8 - 2017-11-21 at 08 19 05

**Comment by frederoni** [comment]
> Rerouting when the laneview was visible on the previous route:

Fixed in https://github.com/mapbox/mapbox-navigation-ios/pull/873/commits/b1e4a61d34d0977eae671634d8de73a391480d82
autores

**Comment by bsudekum** [comment]
@frederoni hrm still seeing this:

gif3


Pulled latest, running commit: `647025ebfa73ff8a16f6636a18b71dfd55bc54fd`

**Comment by bsudekum** [comment]
Tested recent commits, looking like it's fixed.

**Comment by frederoni** [comment]
@bsudekum yes, https://github.com/mapbox/mapbox-navigation-ios/pull/873/commits/1851ee1f0dc67354148e68c3f4479c54eca324f5 fixed the incorrect layout. This PR should be good to merge.

**Pull request merged**
