### PR TITLE
Polyline 6 encoding

### PR DESCRIPTION
**Pull request by bsudekum**
Closes: https://github.com/mapbox/mapbox-navigation-ios/issues/631

/cc @1ec5 @frederoni

### CODE REVIEW

**Comment by ericrwolfe** [comment]
Let's hold on this until we have concrete reasons for why this is necessary for improving navigation. Polyline 5 has 1.1m precision, which is already far more precise than what human OSM mappers can even support. The increase from 5 to 6 decimals may lead to geometry payloads being about ~20% larger.

**Comment by 1ec5** [comment]
In that case, should we change the Android navigation SDK to use Polyline 5 for consistency?

**Comment by bsudekum** [comment]
Let's reopen this if it becomes actionable.

**Comment by TNT0305** [comment]
Apologies if this comment should be a new issue (or posted somewhere else altogether).

I'm trying to load a stored directions response (so, a json string) into navigation UI on iOS and on Android.  My initial test json was encoded with polyline(5).  This works perfectly on iOS but not on android (even if I set the RouteOptions.Geometries(DirectionsCriteria.GeometryPolyline) -- the overall shape of the line is correct, but there is no map (I suspect its zoomed *way* out or in).  If I run the same trip with polyline6, the Android version works perfectly, but the iOS version *crashes*.
I understand what I'm trying to do is not the normal use case (that is, running a navigation from a stored route), but is this a known issue or am I doing it wrong?

Thanks!

**Comment by 1ec5** [comment]
Hi @TNT0305, if I’m not mistaken, your polyline5-encoded JSON won’t work on Android because it would decode the polyline according to the encoding that it expects, [which is polyline6](https://github.com/mapbox/mapbox-navigation-android/blob/2026c6e714f3e43c81e1c9610c50ac52e3e090c3/libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/NavigationRoute.java#L587). Conversely, a polyline6 encoding won’t work on iOS because the SDK decodes it according to polyline5 encoding by default. In both cases, a crash is possible if the resulting misinterpreted coordinates fall outside of the valid range. At least on iOS, you can specify the encoding in the route options object, which will affect how the polyline is decoded. If this doesn’t work for you, please open a new issue about it, since this old PR isn’t being monitored. Thanks!

**Comment by 1ec5** [comment]
>  I've tried setting the "ShapeFormat" in the routeOptions of in ios and it doesn't respect what I tell it.

How did you set the route options? NavigationRouteOptions is just a value class. When deserializing the JSON into a Route object, the `geometry` property is decoded based on the `shapeFormat` of the `options` argument passed into `Route(json:waypoints:options:)`:

https://github.com/mapbox/MapboxDirections.swift/blob/2a327934e7032da62feb8eba8dd8595996e33456/MapboxDirections/MBRoute.swift#L36

>  Likeswise, if I pass in a Polyline6 encoded geometry, it crashes regardless of what I pass into the ShapeFormat.

Incidentally, what’s the stack trace at the time of the crash?

/cc @danesfeder

**Comment by TNT0305** [comment]
I'm doing it from xamarin, btw, but here's the code:
```
                NSError err = new NSError();
                var nsDat = NSData.FromString(jsonRoute);

                // Deserialize the json into an nsdictionary
                var deserObj =
(NSDictionary)NSJsonSerialization.Deserialize(nsDat,
NSJsonReadingOptions.AllowFragments, out err);
                //Get the particular route and set the dictionary that is
there (strong typing) to actually be an NSDictionary (cuz it is)
                var routeDict =
(NSDictionary)((NSArray)deserObj["routes"]).GetItem<NSObject>(0);
                //Type the NSDictionary because that's what the MBRoute
contrctor wants and C# doesn;t let you do such a conversion
                var keys = new List<NSString>();
                var vals = new List<NSObject>();
                foreach (var kvp in routeDict)
                {
                    keys.Add((NSString)kvp.Key);
                    vals.Add(kvp.Value);
                }
                //We had to convert the NSDictionary into a typed
NSDictionary<NSString, NSObject> because of the binding, I think
                var myDict = new NSDictionary<NSString,
NSObject>(keys.ToArray(), vals.ToArray());

                var wp = new List<MBWaypoint>() {
                    new MBWaypoint(new CLLocationCoordinate2D(45,-97),0,
"test"),
                    new MBWaypoint(new CLLocationCoordinate2D(45,-98),0,
"test")
                }.ToArray();
                var ro = new MBRouteOptions(wp, "mapbox/driving");
                ro.ShapeFormat = MBRouteShapeFormat.Polyline6;
                ro.RouteShapeResolution = MBRouteShapeResolution.Full;
                ro.IncludesSteps = true;
                ro.IncludesAlternativeRoutes = false;
                ro.IncludesExitRoundaboutManeuver = true;
                ro.IncludesSpokenInstructions = true;
                ro.IncludesSteps = true;
                ro.IncludesVisualInstructions = true;

                // finally, create the route object using the NSDictionary,
waypoints, and new routeOptions
                var route = new MBRoute(myDict, wp, ro);
```
The last line, above, is where the route object is finally created.  I
continue as follows:
```
                var locationManager = new MBNavigationLocationManager();
                if(shouldSimulate)
                    locationManager = new MBSimulatedLocationManager(route);


                var viewController = new MBNavigationViewController(route,
MBDirections.SharedDirections, null, locationManager);
                //PresentViewController(viewController, true, null);
                var window = UIApplication.SharedApplication.KeyWindow;

window.RootViewController.PresentViewController(viewController, false,
null);
```

Bear in mind, this has been a "throwaway" app I've been using just to test
things out...so, disregard the crappy coding style ;)

The exception is:

```
Unhandled Exception:

Foundation.MonoTouchException: Objective-C exception thrown.  Name:
CALayerInvalidGeometry Reason: CALayer position contains NaN: [nan nan]
Native stack trace:
0   CoreFoundation                      0x0000000115a7e29b
__exceptionPreprocess + 331
1   libobjc.A.dylib                     0x00000001168a2735
objc_exception_throw + 48
2   CoreFoundation                      0x0000000115a7e0f5 +[NSException
raise:format:] + 197
3   QuartzCore                          0x000000010ec9d3c7
_ZN2CA5Layer12set_positionERKNS_4Vec2IdEEb + 141
4   QuartzCore                          0x000000010ec8c4b7 -[CALayer
setPosition:] + 57
5   UIKitCore                           0x0000000120718b9d -[UIView
setCenter:] + 268
6   MapboxNavigation                    0x0000000111b55a20
_T016MapboxNavigation0B7MapViewC03mapD36DidFinishRenderingFrameFullyRenderedySbF
+ 192
7   MapboxNavigation                    0x0000000111b55a8b
_T016MapboxNavigation0B7MapViewC17showsUserLocationSbvsToTm + 43
8   Mapbox                              0x0000000111ed60f1
_Z31MGLGeoJSONOptionsFromDictionaryP12NSDictionaryIP8NSStringP11objc_objectE
+ 566347
9   Mapbox                              0x0000000111f92bcb
utrie2_enumForLeadSurrogate_58 + 358389
10  Mapbox                              0x0000000111ffaa3a
utrie2_enumForLeadSurrogate_58 + 783972
11  Mapbox                              0x0000000111eb5d7c
_Z31MGLGeoJSONOptionsFromDictionaryP12NSDictionaryIP8NSStringP11objc_objectE
+ 434390
12  Mapbox                              0x0000000111eb5d2f
_Z31MGLGeoJSONOptionsFromDictionaryP12NSDictionaryIP8NSStringP11objc_objectE
+ 434313
13  GLKit                               0x000000010cdc3fa8 -[GLKView
_display:] + 283
14  Mapbox                              0x0000000111eb66a9
_Z31MGLGeoJSONOptionsFromDictionaryP12NSDictionaryIP8NSStringP11objc_objectE
+ 436739
15  Mapbox                              0x0000000111eb694a
_Z31MGLGeoJSONOptionsFromDictionaryP12NSDictionaryIP8NSStringP11objc_objectE
+ 437412
16  UIKitCore                           0x0000000120734e05
-[UIView(Internal) _didMoveFromWindow:toWindow:] + 1820
17  UIKitCore                           0x00000001207349ab
-[UIView(Internal) _didMoveFromWindow:toWindow:] + 706
18  UIKitCore                           0x00000001207349ab
-[UIView(Internal) _didMoveFromWindow:toWindow:] + 706
19  UIKitCore                           0x0000000120727091
__45-[UIView(Hierarchy) _postMovedFromSuperview:]_block_invoke + 151
20  UIKitCore                           0x0000000120726f70
-[UIView(Hierarchy) _postMovedFromSuperview:] + 804
21  UIKitCore                           0x00000001207379a5
-[UIView(Internal) _addSubview:positioned:relativeTo:] + 1951
22  UIKitCore                           0x000000012077dfc3
__67-[UIViewControllerBuiltinTransitionViewAnimator
animateTransition:]_block_invoke_2 + 49
23  UIKitCore                           0x000000012072fab5
+[UIView(Animation) performWithoutAnimation:] + 90
24  UIKitCore                           0x000000012077df4b
__67-[UIViewControllerBuiltinTransitionViewAnimator
animateTransition:]_block_invoke + 115
25  UIKitCore                           0x0000000120731472
+[UIView(UIViewAnimationWithBlocks)
_setupAnimationWithDuration:delay:view:options:factory:animations:start:animationStateGenerator:completion:]
+ 558
26  UIKitCore                           0x000000012073194f
+[UIView(UIViewAnimationWithBlocks)
animateWithDuration:delay:options:animations:completion:] + 99
27  UIKitCore                           0x000000012077d57d
-[UIViewControllerBuiltinTransitionViewAnimator animateTransition:] + 1738
28  UIKitCore                           0x0000000120388fd1
__56-[UIPresentationController runTransitionForCurrentState]_block_invoke +
3132
29  UIKitCore                           0x000000012003097e
_runAfterCACommitDeferredBlocks + 318
30  UIKitCore                           0x000000012001f424
_cleanUpAfterCAFlushAndRunDeferredBlocks + 384
31  UIKitCore                           0x000000012004e870
_afterCACommitHandler + 135
32  CoreFoundation                      0x00000001159e1037
__CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
33  CoreFoundation                      0x00000001159db4ce
__CFRunLoopDoObservers + 430
34  CoreFoundation                      0x00000001159dbb61 __CFRunLoopRun +
1537
35  CoreFoundation                      0x00000001159db221
CFRunLoopRunSpecific + 625
36  GraphicsServices                    0x000000011bde41dd GSEventRunModal
+ 62
37  UIKitCore                           0x0000000120025115
UIApplicationMain + 140
38  ???                                 0x000000013ba11e7e 0x0 + 5295382142
39  ???                                 0x000000013ba11c13 0x0 + 5295381523
```

Take care, and thanks for the response!

**Comment by TNT0305** [comment]
I'm doing it from xamarin, btw, but here's the code:
```
NSError err = new NSError();
var nsDat = NSData.FromString(jsonRoute);

// Deserialize the json into an nsdictionary
var deserObj = (NSDictionary)NSJsonSerialization.Deserialize(nsDat, NSJsonReadingOptions.AllowFragments, out err);
//Get the particular route and set the dictionary that is there (strong typing) to actually be an NSDictionary (cuz it is)
var routeDict = (NSDictionary)((NSArray)deserObj["routes"]).GetItem<NSObject>(0);
//Type the NSDictionary because that's what the MBRoute contrctor wants and C# doesn;t let you do such a conversion
var keys = new List<NSString>();
var vals = new List<NSObject>();
foreach (var kvp in routeDict)
{
	keys.Add((NSString)kvp.Key);
	vals.Add(kvp.Value);
}
//We had to convert the NSDictionary into a typed NSDictionary<NSString, NSObject> because of the binding, I think
var myDict = new NSDictionary<NSString, NSObject>(keys.ToArray(), vals.ToArray());

var wp = new List<MBWaypoint>() {
	new MBWaypoint(new CLLocationCoordinate2D(45,-97),0, "test"),
	new MBWaypoint(new CLLocationCoordinate2D(45,-98),0, "test")
}.ToArray();
var ro = new MBRouteOptions(wp, "mapbox/driving");
ro.ShapeFormat = MBRouteShapeFormat.Polyline6;
ro.RouteShapeResolution = MBRouteShapeResolution.Full;
ro.IncludesSteps = true;
ro.IncludesAlternativeRoutes = false;
ro.IncludesExitRoundaboutManeuver = true;
ro.IncludesSpokenInstructions = true;
ro.IncludesSteps = true;
ro.IncludesVisualInstructions = true;

// finally, create the route object using the NSDictionary, waypoints, and new routeOptions
var route = new MBRoute(myDict, wp, ro);```
```

Bear in mind, this has been a "throwaway" app I've been using just to test things out...so, disregard the crappy coding style ;)

The exception is:

```
Unhandled Exception:

Foundation.MonoTouchException: Objective-C exception thrown.  Name: CALayerInvalidGeometry Reason: CALayer position contains NaN: [nan nan]
Native stack trace:
	0   CoreFoundation                      0x0000000115a7e29b __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x00000001168a2735 objc_exception_throw + 48
	2   CoreFoundation                      0x0000000115a7e0f5 +[NSException raise:format:] + 197
	3   QuartzCore                          0x000000010ec9d3c7 _ZN2CA5Layer12set_positionERKNS_4Vec2IdEEb + 141
	4   QuartzCore                          0x000000010ec8c4b7 -[CALayer setPosition:] + 57
	5   UIKitCore                           0x0000000120718b9d -[UIView setCenter:] + 268
	6   MapboxNavigation                    0x0000000111b55a20 _T016MapboxNavigation0B7MapViewC03mapD36DidFinishRenderingFrameFullyRenderedySbF + 192
	7   MapboxNavigation                    0x0000000111b55a8b _T016MapboxNavigation0B7MapViewC17showsUserLocationSbvsToTm + 43
	8   Mapbox                              0x0000000111ed60f1 _Z31MGLGeoJSONOptionsFromDictionaryP12NSDictionaryIP8NSStringP11objc_objectE + 566347
	9   Mapbox                              0x0000000111f92bcb utrie2_enumForLeadSurrogate_58 + 358389
	10  Mapbox                              0x0000000111ffaa3a utrie2_enumForLeadSurrogate_58 + 783972
	11  Mapbox                              0x0000000111eb5d7c _Z31MGLGeoJSONOptionsFromDictionaryP12NSDictionaryIP8NSStringP11objc_objectE + 434390
	12  Mapbox                              0x0000000111eb5d2f _Z31MGLGeoJSONOptionsFromDictionaryP12NSDictionaryIP8NSStringP11objc_objectE + 434313
	13  GLKit                               0x000000010cdc3fa8 -[GLKView _display:] + 283
	14  Mapbox                              0x0000000111eb66a9 _Z31MGLGeoJSONOptionsFromDictionaryP12NSDictionaryIP8NSStringP11objc_objectE + 436739
	15  Mapbox                              0x0000000111eb694a _Z31MGLGeoJSONOptionsFromDictionaryP12NSDictionaryIP8NSStringP11objc_objectE + 437412
	16  UIKitCore                           0x0000000120734e05 -[UIView(Internal) _didMoveFromWindow:toWindow:] + 1820
	17  UIKitCore                           0x00000001207349ab -[UIView(Internal) _didMoveFromWindow:toWindow:] + 706
	18  UIKitCore                           0x00000001207349ab -[UIView(Internal) _didMoveFromWindow:toWindow:] + 706
	19  UIKitCore                           0x0000000120727091 __45-[UIView(Hierarchy) _postMovedFromSuperview:]_block_invoke + 151
	20  UIKitCore                           0x0000000120726f70 -[UIView(Hierarchy) _postMovedFromSuperview:] + 804
	21  UIKitCore                           0x00000001207379a5 -[UIView(Internal) _addSubview:positioned:relativeTo:] + 1951
	22  UIKitCore                           0x000000012077dfc3 __67-[UIViewControllerBuiltinTransitionViewAnimator animateTransition:]_block_invoke_2 + 49
	23  UIKitCore                           0x000000012072fab5 +[UIView(Animation) performWithoutAnimation:] + 90
	24  UIKitCore                           0x000000012077df4b __67-[UIViewControllerBuiltinTransitionViewAnimator animateTransition:]_block_invoke + 115
	25  UIKitCore                           0x0000000120731472 +[UIView(UIViewAnimationWithBlocks) _setupAnimationWithDuration:delay:view:options:factory:animations:start:animationStateGenerator:completion:] + 558
	26  UIKitCore                           0x000000012073194f +[UIView(UIViewAnimationWithBlocks) animateWithDuration:delay:options:animations:completion:] + 99
	27  UIKitCore                           0x000000012077d57d -[UIViewControllerBuiltinTransitionViewAnimator animateTransition:] + 1738
	28  UIKitCore                           0x0000000120388fd1 __56-[UIPresentationController runTransitionForCurrentState]_block_invoke + 3132
	29  UIKitCore                           0x000000012003097e _runAfterCACommitDeferredBlocks + 318
	30  UIKitCore                           0x000000012001f424 _cleanUpAfterCAFlushAndRunDeferredBlocks + 384
	31  UIKitCore                           0x000000012004e870 _afterCACommitHandler + 135
	32  CoreFoundation                      0x00000001159e1037 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
	33  CoreFoundation                      0x00000001159db4ce __CFRunLoopDoObservers + 430
	34  CoreFoundation                      0x00000001159dbb61 __CFRunLoopRun + 1537
	35  CoreFoundation                      0x00000001159db221 CFRunLoopRunSpecific + 625
	36  GraphicsServices                    0x000000011bde41dd GSEventRunModal + 62
	37  UIKitCore                           0x0000000120025115 UIApplicationMain + 140
	38  ???                                 0x000000013ba11e7e 0x0 + 5295382142
	39  ???                                 0x000000013ba11c13 0x0 + 5295381523
```

Take care, and thanks for the response!

**Comment by 1ec5** [comment]
I moved this discussion to #1924 so I don’t have to keep returning to this old PR. 🙂

**Pull request closed without merging**
