### PR TITLE
Disable 32-bit architectures

### PR DESCRIPTION
**Pull request by 1ec5**
Unfortunately, MapboxNavigationNative is only available for arm64 and x86_64 architectures at the moment, despite the default and overwhelmingly common architectures being arm64, arm64e, armv7, and armv7s. Until we can upgrade to a release of MapboxNavigationNative that supports the right architectures, we’ll have to limit MapboxCoreNavigation and MapboxNavigation to the same set of architectures.

These changes only fix the issue for Carthage; #2416 includes a fix for CocoaPods.

/cc @mapbox/navigation-ios

### CODE REVIEW

**Comment by zugaldia** [comment]
Where are we tracking re-adding the missing archs?

**Comment by 1ec5** [comment]
We’re tracking that issue upstream, internally, as part of the MapboxNavigationNative project.

**Comment by Udumft** [comment]
This fix is blocking [amazon metrics](https://github.com/mapbox/navigation-sdks/issues/408) collecting, because it requires a release app built for device farm running, and it is failing due to missing arch.

**Comment by Udumft** [comment]
This fix is blocking the metrics collecting task I am working on right now, because it require a release app to be built to run on a device, and missing ARMv7 arch is blocking the CI process.

**Comment by zugaldia** [comment]
Good catch @Udumft !

**Pull request merged**
