### PR TITLE
Move example app to pods

### PR DESCRIPTION
**Pull request by bsudekum**
It's time. Carthage is just not working for us or other developers for getting the example app up and running easily and quickly. 

There are a few last carthage warnings to take care of:

image

/cc @1ec5 @frederoni @ericrwolfe @JThramer

### CODE REVIEW

**Comment by 1ec5** [comment]
Do we really want to relive the pain of having half the repository under Carthage and the other half under CocoaPods?

> Carthage is just not working for us or other developers for getting the example app up and running easily and quickly.

Sounds like we need a full-fledged example application, in its own repository, that developers can spin up without figuring out which branch to check out or getting distracted by the development-only content in this repository.

**Comment by LuAndreCast** [comment]
Is this repo Carthage friendly? 
Running the project in Carthage its working but publishing to the store gives a world of problems like "unsupported architectures, bundles with invalid folder names  MapboxNavigation.framework/Frameworks/".

**Comment by bsudekum** [comment]
@LuAndreCast yes, check out our [installation documentation](https://github.com/mapbox/mapbox-navigation-ios#installation). I'll check out the specific bug while pushing to store.

**Comment by frederoni** [comment]
@LuAndreCast also, make sure you follow these [steps](https://github.com/Carthage/Carthage#if-youre-building-for-ios-tvos-or-watchos) before you publish your app.

**Comment by LuAndreCast** [comment]
@bsudekum thanks the Carthage seems a little confusing. (Part 3 below). 

_Follow the rest of Carthage’s iOS integration instructions. Your application target’s Embedded Frameworks should include MapboxNavigation.framework and MapboxCoreNavigation.framework._

are we inserting into our project MapboxNavigation.framework and MapboxCoreNavigation.framework only ? or all frameworks?

asking since I notice MapboxNavigation.framework has a folder "Framework" that contains all other frameworks

**Comment by LuAndreCast** [comment]
@frederoni do we need to use all frameworks or only the below in our Carthage setup?
- MapboxNavigation.framework 
- MapboxCoreNavigation.framework 

also, is the below step really needed ? (adding dsym files..) 

_Additionally, you'll need to copy debug symbols for debugging and crash reporting on OS X.

On your application target’s “Build Phases” settings tab, click the “+” icon and choose “New Copy Files Phase”.
Click the “Destination” drop-down menu and select “Products Directory”.
For each framework you’re using, drag and drop its corresponding dSYM file._

**Comment by frederoni** [comment]
@LuAndreCast you need to add all underlying dependencies as well.

Assuming you have Bitcode enabled, you'd have to download the dSym after iTC finished processing the build. Use the `configuration --Debug` flag w/ Carthage `bootstrapt/update` to include the symbols.

> For each framework you’re using, drag and drop its corresponding dSYM file._

You shouldn't have to do this.

**Comment by LuAndreCast** [comment]
@frederoni  thanks for quick reply. 
So I setup Carthage like the screenshots attached and executed the below commands
  carthage update --platform iOS
  carthage build -configuration Debug
  carthage bootstrap

screen shot 2017-12-11 at 11 35 06 am
screen shot 2017-12-11 at 11 37 40 am

**Comment by LuAndreCast** [comment]
I also dragged and drop all frameworks from **_(Carthage/Build/iOS)_** to **_Linked Frameworks and Libraries_**

**Comment by frederoni** [comment]
@LuAndreCast Looks correct 👍 

Note that both the `update` and `bootstrap` command will build the dependencies unless you specify `--no-build`. Use update if you want to update the dependencies and bootstrap when you want to install the same versions that your `Cartfile.resolved` is pointing to.

I use
```carthage bootstrap --platform ios --cache-builds --configuration Debug --no-use-binaries```
for bootstrapping and
```carthage update --platform ios --cache-builds --configuration Debug --no-use-binaries```
for updating.

The `--cache-builds` flag really speed things up the second time.

**Comment by LuAndreCast** [comment]
thanks @frederoni I'll was able to run and now when I upload the app build to the store and I get few errors.

attached please find the errors getting. suggestions? 
screenshot_12_11_17__12_00_pm

**Comment by LuAndreCast** [comment]
GM @bsudekum @frederoni , any suggestions on the error you get when publishing to the store with Carthage? 

_**"Invalid Bundle: The Bundle "MapboxNavigation.framework" contains disallowed nested bundles."**_

**Comment by Sealos** [comment]
Run this where the Carthage folder is:
```bash
rm -rf "Carthage/Build/iOS/MapboxNavigation.framework/Frameworks"
```

The problem is that the build is including the frameworks on the MapboxNavigation.framework. Most likely you will also have to add the Mapbox dependencies to your "Copy Carthage Files" build phase.

**Comment by LuAndreCast** [comment]
@Sealos thank you so much!! if can hug ya, I would!! thanks again guys!

**Comment by bsudekum** [comment]
@frederoni are there any take aways here? Should we update the readme/change our xcode proj?

**Comment by frederoni** [comment]
> Run this where the Carthage folder is located:
rm -rf "Carthage/Build/iOS/MapboxNavigation.framework/Frameworks"

I wonder if this is caused by the fact that we have a copy phase not only for the application target but also the framework target. 🤔 

<details>

screenshot 2017-12-12 18 20 41

</details>

**Comment by 1ec5** [comment]
Yes, I think that’s the problem. Let’s continue tracking this issue in #927, since it’s off-topic for this pull request.

**Comment by JThramer** [comment]
Little bit late to this party, but I think I agree with @1ec5's assessment here: https://github.com/mapbox/mapbox-navigation-ios/pull/804#issuecomment-342675785

**Comment by 1ec5** [comment]
#932 tracks separating the example applications from this repository. The resulting project can use CocoaPods if that’s easier to get started with.

**Comment by bsudekum** [comment]
Keeping pods for now.

**Pull request closed without merging**
