### PR TITLE
Issue with access control for a string extension on MapboxCoreNavigation

### PR DESCRIPTION
**Pull request by AFcgi**
I get an compiler error that the `wholeRange` needs another access control to use them.

### CODE REVIEW

**Comment by bsudekum** [comment]
This should be fixed by https://github.com/mapbox/mapbox-navigation-ios/pull/632. @AFcgi can you verify this by testing master? If this is case, we'll put out a new release.

/cc @1ec5 @fred

**Comment by 1ec5** [comment]
I snuck #632 in when pushing v0.8.0 to CocoaPods, but it turns out the podspec refers to the tag (which doesn't have the fix), so we do need to put out a new patch release for CocoaPods.

**Comment by bsudekum** [comment]
@1ec5 so is this PR necessary?

**Comment by AFcgi** [comment]
@bsudekum I don't test it. But I think the #632 is correct.

**Comment by 1ec5** [comment]
Closing in favor of #665.

**Pull request closed without merging**
