### PR TITLE
Replace maneuver arrow

### PR DESCRIPTION
**Pull request by frederoni**
WIP #326 

- [ ] Replace the icon with a good looking one
- [ ] Add styling capabilities to the maneuver arrow and shaft
- [ ] Test

@bsudekum @ericrwolfe 👀

### CODE REVIEW

**Comment by bsudekum** [comment]
We should also figure out a better layer order here. How does it look underneath street labels?

**Comment by ericrwolfe** [comment]
Would love to see 2 arrowheads: a white one (or one that matches the main stroke) on top, with one that matches the case below and slightly increased in size to roughly match the case width. Also, the current arrowhead looks a little on the small side.

Also, we should change the line cap to `.butt`.

**Comment by 1ec5** [comment]
> We should also figure out a better layer order here. How does it look underneath street labels?

Placing the maneuver arrow below any shields, exit numbers, or street labels would be a simple fix. However, I’m concerned that putting anything atop the arrow would make the arrow more difficult to spot, making it look even more like a street:

liberty 2nd

Is there a good use case for reading the current road name off the base map, especially given that a label displays the same information, unrotated, at a consistent location on the screen?

**Comment by bsudekum** [comment]
Updated this with a new a white triangle:
simulator screen shot aug 1 2017 11 08 56 am

**Comment by ericrwolfe** [comment]
That new arrow looks so much better 😄

**Comment by ericrwolfe** [comment]
> Add styling capabilities to the maneuver arrow and shaft

Let's do this as a separate PR cc @frederoni

**Pull request merged**
